site_name: Elembo Docs 
nav:
- Accueil: index.md
- Architecture: architecture.md
- Base de données: database.md
- API: api.md
- DevOps: devops.md
theme: 
  name: 'readthedocs'
  color_mode: 'dark'
  nav_style: 'dark'